services:
  vertex-vector-mcp:
    image: vertex/vertexmemory-mcp
    build: api/
    environment:
      - USER
    env_file:
      - api/.env
    ports:
      - "8765:8765"
    volumes:
      - ./api:/usr/src/vertexmemory
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
  vertexmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: vertex/vertexmemory-ui:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_USER_ID=${USER}
